<?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?><br />
<?php if ($this->getInfo()->getLastTransId() == ''): ?>
    <em><?php echo Mage::helper('zupago')->__('You will be redirected to ZuPago HyBrid (HD) Wallet side upon placing an order.') ?></em>
<?php else: ?>
    <?php echo Mage::helper('zupago')->__('ZuPago HyBrid (HD) Wallet transaction id %s', $this->htmlEscape($this->getInfo()->getLastTransId())) ?><br />
<?php endif; ?>
